#!/usr/bin/env python3
"""
Generate site/s2t.js: a char-level Simplified -> Traditional Chinese
map, used so users can type queries in Simplified Chinese against a
corpus (CBETA) that is almost entirely in Traditional Chinese.

This is a 1:1 character map, not OpenCC's full phrase-aware conversion:
a handful of simplified characters that map to different traditional
characters depending on context (e.g. 干 -> 幹/乾/干) will only ever
convert to one of them. That's an acceptable tradeoff for a search
index (queries are typically short, and being able to find some
matches beats requiring users to already know the traditional form).

Requires: pip install opencc-python-reimplemented

Usage:
    python3 scripts/gen_s2t_map.py
"""
import json
from pathlib import Path

from opencc import OpenCC


def main():
    cc = OpenCC("s2t")
    mapping = {}
    for lo, hi in [(0x4E00, 0x9FFF), (0x3400, 0x4DBF)]:
        for cp in range(lo, hi + 1):
            ch = chr(cp)
            conv = cc.convert(ch)
            if conv != ch and len(conv) == 1:
                mapping[ch] = conv

    out_path = Path(__file__).resolve().parent.parent / "site" / "s2t.js"
    with out_path.open("w", encoding="utf-8") as f:
        f.write("// Auto-generated by scripts/gen_s2t_map.py - do not edit by hand\n")
        f.write("const S2T_MAP = " + json.dumps(mapping, ensure_ascii=False, separators=(",", ":")) + ";\n")
        f.write(
            "\nfunction toTraditional(text) {\n"
            "  let out = '';\n"
            "  for (const ch of text) out += S2T_MAP[ch] || ch;\n"
            "  return out;\n"
            "}\n"
        )
    print(f"Wrote {out_path} ({len(mapping)} mapped characters)")


if __name__ == "__main__":
    main()
