#!/usr/bin/env python3
"""
Generate site/t2s.js: a char-level Traditional -> Simplified map, used to
display CBETA texts (almost entirely Traditional) in Simplified Chinese
by default in the reader, with a toggle back to the original Traditional.

Same 1:1 char-map tradeoff as scripts/gen_s2t_map.py: no phrase-aware
context, but small, deterministic, and good enough for display purposes.
Generated independently from s2t (not by inverting it) because the
Traditional->Simplified and Simplified->Traditional mappings are not
exact inverses of each other (several distinct traditional characters
collapse to the same simplified one).

Requires: pip install opencc-python-reimplemented

Usage:
    python3 scripts/gen_t2s_map.py
"""
import json
from pathlib import Path

from opencc import OpenCC


def main():
    cc = OpenCC("t2s")
    mapping = {}
    for lo, hi in [(0x4E00, 0x9FFF), (0x3400, 0x4DBF)]:
        for cp in range(lo, hi + 1):
            ch = chr(cp)
            conv = cc.convert(ch)
            if conv != ch and len(conv) == 1:
                mapping[ch] = conv

    out_path = Path(__file__).resolve().parent.parent / "site" / "t2s.js"
    with out_path.open("w", encoding="utf-8") as f:
        f.write("// Auto-generated by scripts/gen_t2s_map.py - do not edit by hand\n")
        f.write("const T2S_MAP = " + json.dumps(mapping, ensure_ascii=False, separators=(",", ":")) + ";\n")
        f.write(
            "\nfunction toSimplified(text) {\n"
            "  let out = '';\n"
            "  for (const ch of text) out += T2S_MAP[ch] || ch;\n"
            "  return out;\n"
            "}\n"
        )
    print(f"Wrote {out_path} ({len(mapping)} mapped characters)")


if __name__ == "__main__":
    main()
